name: Code validator
on: [push]
jobs:
  Dependencies:
    name: 'Install dependancies'
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update && sudo apt install curl libx11-dev libxmu-dev libxi-dev libgl-dev libopenal-dev
  CSFML-installation:
    name: 'Install CSFML from sources'
    runs-on: ubuntu-latest
    needs: [Dependencies]
    steps:
      - run: curl -Lo SFML.zip https://www.sfml-dev.org/files/SFML-2.5.1-sources.zip
      - run: pwd
      - run: ls
      - run: unzip -qq -o SFML.zip
      - run: mv SFML-* SFML
      - run: ls SFML/
      - run: |
        cd SFML
        cmake .
        make
        make install
      - run: curl -Lo CSFML.zip https://www.sfml-dev.org/files/CSFML-2.5.1-sources.zip
      - run: unzip -qq -o CSFML.zip
      - run: mv CSFML-* CSFML
      - run: cd CSFML
      - run: cmake -DSFML_ROOT="../SFML" -DSFML_INCLUDE_DIR="../SFML/include" -DCMAKE_MODULE_PATH="../SFML/cmake/Modules" .
      - run: make
      - run: make install
      - run: cd ..
      - run: echo "/usr/local/lib/" > /etc/ld.so.conf.d/csfml.conf
      - run: ldconfig
  Compilation:
    name: Compile code with Makefile
    runs-on: ubuntu-latest
    needs: [Dependencies, CSFML-installation]
    steps:
      - uses: actions/checkout@v3
      - run: make

